// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 11. 4. 오후 4:00:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/user/mdh/project/new-sajuline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/user/mdh/project/new-sajuline/frontend/composables/**/*.{js,ts,mjs}","C:/Users/user/mdh/project/new-sajuline/frontend/utils/**/*.{js,ts,mjs}","C:/Users/user/mdh/project/new-sajuline/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/mdh/project/new-sajuline/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;