// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/17/2025, 5:33:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/plugins/**/*.{js,ts,mjs}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/composables/**/*.{js,ts,mjs}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/utils/**/*.{js,ts,mjs}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jino/Library/CloudStorage/Dropbox/JINO/sajuline/new-sajuline/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;